### ISSUE TITLE
Back office allow these fields to be nullable

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#130]
Selections ticket_type, payment_value, payment_due_date
Applications coding_test_start

**Comment by cimendes** [comment]
#143

**Comment by hcastilho** [comment]
The fields not being nullable (in the django model) prevents saving in the back office.

**Comment by Gustavo-SF** [comment]
Got it. Seems like `null=True` doesn't do much, and we need to specify it as `blank=True` ([SO question](https://stackoverflow.com/questions/7341066/can-i-make-an-admin-field-not-required-in-django-without-creating-a-form)). 

Although Applications become possible this way, `Selection` since its user is non-editable, we can't add it in the back office. Unless we make it editable. Do we?
