### ISSUE TITLE
impose memory limit on exercise notebooks

### ISSUE THREAD

**Issue by buedaswag** [LDSSA/portal#188]
* exercise notebooks need to run on a limited amount of ram
* if an exercise notebook takes up too much ram, the portal will not be able to grade it
* we need to define how much ram is the limit
* we need to enforce this limit in the cicd pipeline

**Comment by cimendes** [comment]
TO DO: check how to impose this limit on CircleCI and on Kubernetes

**Comment by cimendes** [comment]
an option: use procps to check max memory used by a process and exit if above limit: https://man7.org/linux/man-pages/man1/procps.1.html

**Comment by cimendes** [comment]
Option: impose memory limit on docker command in CircleCI !!!!

**Comment by cimendes** [comment]
The grading of BLU09 exercise notebooks consistently fails due to the notebooks consuming too much memory and crashing the containers that run the grading.
This happens when more than one grading container is running.
On my pc, running the exercise notebook took an extra 4.5gb of ram. The cluster that runs the containers for the portal and grading has 8gb of ram in total.
This means that only one BLU09 grading container can run at a time.

To overcome this problem, several alternatives were mentioned:

Limit grading to one container at a time through changing the code for the portal
Limit grading to one container at a time through a slack channel where students coordinate with each other to guarantee that only one student is grading at a time
Redeploy the cluster on a machine with more ram (this would mean redeploying the portal and i, Miguel anticipate would take several days of full time work to accomplish, therefore in my opinion is not practical)
Ask the students to submit the notebooks as soon as possible
Extend the deadline for submissions
Manually grade and manually set the grade on the portal for each notebook
Next steps

Evaluate option 1’s feasibility. If its not feasible then evaluate what other options are available, discuss with other stakeholders, decide and implement
Coordinate with teaching so that future BLUs have more manageable ram requirements (what would a good amount of ram be?)
More issues

https://github.com/LDSSA/portal/issues/188
https://github.com/LDSSA/ldsagrader/issues/7
