### ISSUE TITLE
Learning unit descriptions in students view don't have width limit

### ISSUE THREAD

**Issue by hcastilho** [LDSSA/portal#20]

**Comment by Juliana-R** [comment]
This issue has gone > 7 months without action and will therefore be closed. Reopen if necessary.

**Comment by hcastilho** [comment]
Still valid reopening.
Hopefully, we will have resources to deal with these non-critical but quality-of-life issues.

**Comment by dbsousa01** [comment]
Just documenting the issue. 
The issue is that in the SLU page, the description text is not bound with the width of the column. Because of this the text never breaks to the next line, as seen below
![image](https://user-images.githubusercontent.com/19359518/115032635-6ed10180-9ec1-11eb-99b7-6456f72c2469.png)

**Comment by dbsousa01** [comment]
After the fix (still local, will open a PR soon). It's staying like this 
![image](https://user-images.githubusercontent.com/19359518/115034221-29adcf00-9ec3-11eb-88fa-19c8b584e925.png)

**Comment by cimendes** [comment]
Related to this issue, in the user section the Deploy Key is also running away from the screen. 

It's important to guarantee that no new lines are added to the strings in this one. Maybe you could spread your magic @dbsousa01? 

![image](https://user-images.githubusercontent.com/15690332/115111114-9930c680-9f76-11eb-8e86-95bfeb1ffd41.png)

**Comment by dbsousa01** [comment]
I've created a PR that addresses the first issue, however, I wasn't successful in breaking the deploy key into several lines. I think the problem is a bit different since the deploy key is a single word. I've looked and tried [this](https://getbootstrap.com/docs/5.0/utilities/text/#word-break) but with no success. 
Might need some help on this @hcastilho

**Comment by hcastilho** [comment]
Probably the best way to deal with that would be to add the deploy key to the user form as read-only.
Lets keep this in mind to deal with later.
